package cn.kepu.ability.common.shortmessage;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import cn.kepu.utils.PropertyConfigureUtils;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * SmsOperatorImpService service = new SmsOperatorImpService();
 * ISmsOperator portType = service.getSmsOperatorImpPort();
 * portType.getReport(...);
 * </pre>
 * 
 * </p>
 * 
 */
//@WebServiceClient(name = "SmsOperatorImpService", targetNamespace = "http://sms.jwsserver.server.ema.ctc.com/", wsdlLocation = "http://159.226.2.3:8080/ema/webService/smsOper?wsdl")
@WebServiceClient(name = "SmsOperatorImpService", targetNamespace = "http://sms.jwsserver.server.ema.ctc.com/")
public class SmsOperatorImpService extends Service {

	private final static URL SMSOPERATORIMPSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(cn.kepu.ability.common.shortmessage.SmsOperatorImpService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = cn.kepu.ability.common.shortmessage.SmsOperatorImpService.class
					.getResource(".");
//			url = new URL(baseUrl,
//					"http://159.226.2.3:8080/ema/webService/smsOper?wsdl");
			url = new URL(baseUrl,
					PropertyConfigureUtils.getString("system.message.server.ip").trim());
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: "+PropertyConfigureUtils.getString("system.message.server.ip").trim()+", retrying as a local file");
			logger.warning(e.getMessage());
			e.printStackTrace();
		}
		SMSOPERATORIMPSERVICE_WSDL_LOCATION = url;
	}

	public SmsOperatorImpService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SmsOperatorImpService() {
		super(SMSOPERATORIMPSERVICE_WSDL_LOCATION, new QName(
				"http://sms.jwsserver.server.ema.ctc.com/",
				"SmsOperatorImpService"));
	}

	/**
	 * 
	 * @return returns ISmsOperator
	 */
	@WebEndpoint(name = "SmsOperatorImpPort")
	public ISmsOperator getSmsOperatorImpPort() {
		return super.getPort(new QName(
				"http://sms.jwsserver.server.ema.ctc.com/",
				"SmsOperatorImpPort"), ISmsOperator.class);
	}

}
